-- SYSTEM계정에서 계정 생성
-- hr : sql developer-system_01계정에서 계정생성안해도 되고, 3.락해제 5.비밀번호변경만 한다.

-- 1. 계정생성 : team1_ict05 계정생성
-- create user <계정이름> identified by <계정암호> default tablespace users;
create user  team1_ict05 identified by yaksok default tablespace users;

-- 2. 사용자 권한 부여
-- grant [시스템 권한] to [계정];
grant connect, resource, create view to team1_ict05;


-- 3. 락 해제
-- alter user <계정이름> account unlock;
alter user team1_ict05 account unlock;

-- 4. 계정 잘못만든 경우 계정, 객체 삭제하기 
-- drop user <계정이름> cascade;
-- drop user team1_ict05 cascade; 

-- 5. 패스워드 변경
-- alter user <계정이름> identified by <패스워드>;
-- alter user team1_ict05 identified by yaksok; 

-------------------------------------------------------------------------
-- 테이블 생성
CREATE TABLE MEMBER_TB (
	MB_ID				NUMBER(9)		PRIMARY KEY,
	MB_NAME				VARCHAR2(36),	
	MB_EMAIL			VARCHAR2(50)	NOT NULL,	
	MB_PASSWORD			VARCHAR2(50)	NOT NULL,	
	MB_GRADE			VARCHAR2(20)	DEFAULT 'ORDINARY' NOT NULL,	
	MB_WRITER_ID		NUMBER(4)		NOT NULL,	
	MB_REG_DATE			DATE			NOT NULL,	
	MB_MODIFY_ID		NUMBER(4),	
	MB_MODIFY_DATE		DATE
);

CREATE TABLE MEMBER_PROFILE_TB (
	MBP_ID				NUMBER(4)		PRIMARY KEY,
	MB_ID				NUMBER(4)		NOT NULL,
	MBS_ID				NUMBER(9),	
	MBP_HEIGHT			NUMBER(3)		NOT NULL,
	MBP_WEIGHT			NUMBER(3)		NOT NULL,
	MBP_AGE				NUMBER(3)		NOT NULL,
	MBP_DISEASE			VARCHAR2(100),	
	MBP_INT_PILL		VARCHAR2(100),	
	MBP_WRITER_ID		NUMBER(4)		NOT NULL,
	MBP_REG_DATE		DATE			NOT NULL,
	MBP_MODIFY_ID		NUMBER(4),	
	MBP_MODIFY_DATE		DATE,
	CONSTRAINT MEMBER_PROFILE_TB FOREIGN KEY (MB_ID) REFERENCES MEMBER_TB (MB_ID),
	CONSTRAINT MEMBER_PROFILE_TB2 FOREIGN KEY (MBS_ID) REFERENCES MEMBER_SURVEY_TB (MBS_ID)
);

CREATE TABLE MEMBER_DRUG_TB (
	MBD_ID				NUMBER(9)		PRIMARY KEY,
	MB_ID 				NUMBER(9)		NOT NULL,
	DR_ID				NUMBER(9)		NOT NULL,
	MBD_DRUG_NAME		VARCHAR2(100),	
	MBD_DRUG_EFFECT		CLOB,			
	MBD_WRITER_ID		NUMBER(4)		NOT NULL,
	MBD_REG_DATE		DATE			NOT NULL,
	MBD_MODIFY_ID		NUMBER(4),	
	MBD_MODIFY_DATE		DATE,
	CONSTRAINT MEMBER_DRUG_TB FOREIGN KEY (MB_ID) REFERENCES MEMBER_TB (MB_ID),
	CONSTRAINT MEMBER_DRUG_TB2 FOREIGN KEY (DR_ID) REFERENCES DRUG_TB (DR_ID)
);
-- 제약 정보 테이블
CREATE TABLE DRUG_TB (
	DR_ID				NUMBER(9)		PRIMARY KEY,
	DR_ENTERPRISE		VARCHAR2(200),	
	DR_PRODUCT			VARCHAR2(500),
	DR_STATEMENT_ID		NUMBER(38),
	DR_REGIST_DATE		DATE,
	DR_EXPIRATION_DATE	VARCHAR2(200),
	DR_SUNGSANG			VARCHAR2(2000),
	DR_SERVE_USE		VARCHAR2(1500),
	DR_INTAKE_HINT		CLOB,
	DR_MAIN_FUNCTION	CLOB,
	DR_PRESERVATION		VARCHAR2(1500),
	DR_BASE_STANDARD	CLOB
);


CREATE TABLE QNA_TB (
	QA_ID				NUMBER(9)		PRIMARY KEY,
	MB_ID				NUMBER(4)		NOT NULL,
	DR_ID				NUMBER,	
	QA_TITLE			VARCHAR2(255)	NOT NULL,	
	QA_CONTENT			CLOB			NOT NULL,	
	QA_PRIVATE			CHAR(1)			NOT NULL,	
	QA_ANSWER			CLOB,	
	QA_ANSWER_DATE		DATE,	
	QA_READCOUNT		NUMBER			DEFAULT 0 NOT NULL,	
	QA_SHOW				CHAR(1)			DEFAULT 'Y' NOT NULL,	
	QA_WRITER_ID		NUMBER(4)		NOT NULL,	
	QA_REG_DATE			DATE			NOT NULL,	
	QA_MODIFY_ID		NUMBER(4),	
	QA_MODIFY_DATE		DATE,
	CONSTRAINT QNA_TB FOREIGN KEY (MB_ID) REFERENCES MEMBER_TB(MB_ID),
	CONSTRAINT QNA_TB2 FOREIGN KEY (DR_ID) REFERENCES DRUG_TB(DR_ID)
);

CREATE TABLE REVIEW_TB (
	RV_ID				NUMBER(4)		PRIMARY KEY,
	MB_ID				NUMBER(4)		NOT NULL,
	DR_ID				NUMBER			NOT NULL,
	MB_NAME				VARCHAR2(36)	NOT NULL,
	RV_CONTENT			VARCHAR2(500)	NOT NULL,
	RV_RATING			NUMBER(4,1)		NOT NULL,
	RV_SHOW				CHAR(1)			DEFAULT 'Y',
	RV_READCOUNT		NUMBER(4)		DEFAULT 0,
	RV_WRITER_ID		NUMBER(4)		NOT NULL,
	RV_REG_DATE			DATE			NOT NULL,
	RV_MODIFY_ID		NUMBER(4),
	RV_MODIFY_DATE		DATE,
	CONSTRAINT REVIEW_TB FOREIGN KEY (MB_ID) REFERENCES MEMBER_TB(MB_ID),
	CONSTRAINT REVIEW_TB2 FOREIGN KEY (DR_ID) REFERENCES DRUG_TB(DR_ID)
);

CREATE TABLE FAQ_TB (
	FA_ID				NUMBER(4)		PRIMARY KEY,
	FA_TITLE			VARCHAR2(50)	NOT NULL,
	FA_CONTENT			VARCHAR2(200)	NOT NULL,
	FA_SHOW				CHAR(1)			DEFAULT 'Y',
	FA_WRITER_ID		NUMBER(4)		NOT NULL,
	FA_REG_DATE			DATE			NOT NULL,
	FA_MODIFY_ID		NUMBER(4),
	FA_MODIFY_DATE		DATE
);

CREATE TABLE MEMBER_SURVEY_TB (
	MBS_ID				NUMBER(9)		PRIMARY KEY,
	MB_ID 				NUMBER(9)		NOT NULL,
	MBS_SCORE			NUMBER(9)		NOT NULL,
	MBS_SERVEY_DATE		DATE			NOT NULL,
	MBS_WRITER_ID		NUMBER(4)		NOT NULL,
	MBS_REG_DATE		DATE			NOT NULL,
	MBS_MODIFY_ID		NUMBER(4),
	MBS_MODIFY_DATE		DATE,
	CONSTRAINT MEMBER_SURVEY_TB FOREIGN KEY (MB_ID) REFERENCES MEMBER_TB(MB_ID)
);

CREATE TABLE RULE_TB (
	RULE_ID				NUMBER(4)		PRIMARY KEY,
	RULE_AGE			NUMBER(3),
	RULE_INTEREST		VARCHAR(400),
	RULE_DISEASE		VARCHAR(400),
	RULE_RECOMMEND		VARCHAR(400)
);

-----------------------------------------------------------------------------
-- OPEN API - 크롤링 데이터 넣기
-----------------------------------------------------------------------------

-- DR_PRODUCT_DETAIL 테이블 생성 

CREATE TABLE DR_PRODUCT_DETAIL (
    ENTRPS        VARCHAR2(40 char),   -- (26)
    PRDUCT        VARCHAR2(150 char),   -- (109)
    STTEMNT_NO    VARCHAR2(30 char),   -- (15)
    REGIST_DT     VARCHAR2(8 char),   -- YYYYMMDD

    DISTB_PD      VARCHAR2(50 char),   -- (35)
    SRV_USE       VARCHAR2(400 char),   -- (256)
    PRSRV_PD      VARCHAR2(600 char),   -- (473)
    SUNGSANG      VARCHAR2(600 char),   -- (465)

    -- ▼ 긴 텍스트: CLOB (항상 끝)
    INTAKE_HINT1  CLOB,                 -- (1176)
    MAIN_FNCTN    CLOB,                 -- (1849)
    BASE_STANDARD CLOB                  -- (3453)
);
-- 조회
SELECT *
  FROM DR_PRODUCT_DETAIL;

-- 내용 초기화
DELETE FROM DR_PRODUCT_DETAIL;

-- import_db_dr_product_detail.py 실행!

-- 데이터수 조회
SELECT count(*)
  FROM DR_PRODUCT_DETAIL;

-----------------------------------------------------------------------------
-- DR_PRODUCT_DETAIL 데이터 => 
-----------------------------------------------------------------------------
-- 1) 시작값 계산해서 시퀀스 생성
DECLARE
  v_start NUMBER;
BEGIN
  SELECT NVL(MAX(DR_ID),0) + 1 INTO v_start FROM DRUG_TB;
  EXECUTE IMMEDIATE
    'CREATE SEQUENCE DRUG_SEQ START WITH '||v_start||' INCREMENT BY 1 NOCACHE NOCYCLE';
END;

-- 2) 테이블에 넣기
INSERT INTO DRUG_TB (
    DR_ID,
    DR_ENTERPRISE,
    DR_PRODUCT,
    DR_STATEMENT_ID,
    DR_REGIST_DATE,
    DR_EXPIRATION_DATE,
    DR_SUNGSANG,
    DR_SERVE_USE,
    DR_INTAKE_HINT,
    DR_MAIN_FUNCTION,
    DR_PRESERVATION,
    DR_BASE_STANDARD
)
SELECT
	DRUG_SEQ.NEXTVAL,    
    NULLIF(TRIM(ENTRPS), ''),
    NULLIF(TRIM(PRDUCT), ''),
    CASE WHEN REGEXP_LIKE(TRIM(STTEMNT_NO), '^\d+$')
         THEN TO_NUMBER(TRIM(STTEMNT_NO)) END,
    CASE WHEN REGEXP_LIKE(TRIM(REGIST_DT), '^\d{8}$')
         THEN TO_DATE(TRIM(REGIST_DT), 'YYYYMMDD') END,
    NULLIF(TRIM(DISTB_PD), ''),
    NULLIF(TRIM(SUNGSANG), ''),
    NULLIF(TRIM(SRV_USE), ''),
    TO_CLOB(INTAKE_HINT1),
    MAIN_FNCTN,
    PRSRV_PD,
    BASE_STANDARD
FROM DR_PRODUCT_DETAIL
WHERE REGEXP_LIKE(TRIM(STTEMNT_NO), '^\d+$')
  AND REGEXP_LIKE(TRIM(REGIST_DT), '^\d{8}$');

-- DRUG_TB에 데이터 들어갔는지 확인
SELECT *
  FROM DRUG_TB
 ORDER BY DR_ID;
----------------------------------------------------------------------------------
-- RULE_TB에 기준 데이터 넣기
-- 시퀀스 생성
CREATE SEQUENCE RULE_TB_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
-- 자료 넣기
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 10, '피로/간', '당뇨', '비타민B, 밀크씨슬');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 10, '피로/간', '고혈압/심혈관', '밀크씨슬, 오메가3');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 10, '피로/간', '골다공증/관절', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 10, '피로/간', '위장질환', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 10, '체지방/혈당', '당뇨', '크롬, 알파리포산');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 10, '체지방/혈당', '고혈압/심혈관', '오메가3, 코엔자임Q10');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 10, '체지방/혈당', '골다공증/관절', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 10, '체지방/혈당', '위장질환', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 10, '눈', '당뇨', '루테인, 아스타잔틴');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 10, '눈', '고혈압/심혈관', '루테인, 오메가3');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 10, '눈', '골다공증/관절', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 10, '눈', '위장질환', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 10, '뼈', '당뇨', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 10, '뼈', '고혈압/심혈관', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 10, '뼈', '골다공증/관절', '칼슘, 비타민D');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 10, '뼈', '위장질환', '마그네슘, 비타민D');

INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 20, '피로/간', '당뇨', '비타민B, 밀크씨슬');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 20, '피로/간', '고혈압/심혈관', '밀크씨슬, 오메가3');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 20, '피로/간', '골다공증/관절', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 20, '피로/간', '위장질환', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 20, '체지방/혈당', '당뇨', '크롬, 알파리포산');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 20, '체지방/혈당', '고혈압/심혈관', '오메가3, 코엔자임Q10');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 20, '체지방/혈당', '골다공증/관절', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 20, '체지방/혈당', '위장질환', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 20, '눈', '당뇨', '루테인, 아스타잔틴');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 20, '눈', '고혈압/심혈관', '루테인, 오메가3');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 20, '눈', '골다공증/관절', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 20, '눈', '위장질환', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 20, '뼈', '당뇨', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 20, '뼈', '고혈압/심혈관', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 20, '뼈', '골다공증/관절', '칼슘, 비타민D');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 20, '뼈', '위장질환', '마그네슘, 비타민D');

INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 30, '피로/간', '당뇨', '비타민B, 밀크씨슬');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 30, '피로/간', '고혈압/심혈관', '밀크씨슬, 오메가3');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 30, '피로/간', '골다공증/관절', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 30, '피로/간', '위장질환', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 30, '체지방/혈당', '당뇨', '크롬, 알파리포산');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 30, '체지방/혈당', '고혈압/심혈관', '오메가3, 코엔자임Q10');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 30, '체지방/혈당', '골다공증/관절', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 30, '체지방/혈당', '위장질환', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 30, '눈', '당뇨', '루테인, 아스타잔틴');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 30, '눈', '고혈압/심혈관', '루테인, 오메가3');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 30, '눈', '골다공증/관절', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 30, '눈', '위장질환', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 30, '뼈', '당뇨', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 30, '뼈', '고혈압/심혈관', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 30, '뼈', '골다공증/관절', '칼슘, 비타민D');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 30, '뼈', '위장질환', '마그네슘, 비타민D');

INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 40, '피로/간', '당뇨', '비타민B, 밀크씨슬');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 40, '피로/간', '고혈압/심혈관', '밀크씨슬, 오메가3');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 40, '피로/간', '골다공증/관절', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 40, '피로/간', '위장질환', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 40, '체지방/혈당', '당뇨', '크롬, 알파리포산');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 40, '체지방/혈당', '고혈압/심혈관', '오메가3, 코엔자임Q10');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 40, '체지방/혈당', '골다공증/관절', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 40, '체지방/혈당', '위장질환', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 40, '눈', '당뇨', '루테인, 아스타잔틴');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 40, '눈', '고혈압/심혈관', '루테인, 오메가3');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 40, '눈', '골다공증/관절', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 40, '눈', '위장질환', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 40, '뼈', '당뇨', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 40, '뼈', '고혈압/심혈관', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 40, '뼈', '골다공증/관절', '칼슘, 비타민D');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 40, '뼈', '위장질환', '마그네슘, 비타민D');

INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 50, '피로/간', '당뇨', '비타민B, 밀크씨슬');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 50, '피로/간', '고혈압/심혈관', '밀크씨슬, 오메가3');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 50, '피로/간', '골다공증/관절', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 50, '피로/간', '위장질환', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 50, '체지방/혈당', '당뇨', '크롬, 알파리포산');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 50, '체지방/혈당', '고혈압/심혈관', '오메가3, 코엔자임Q10');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 50, '체지방/혈당', '골다공증/관절', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 50, '체지방/혈당', '위장질환', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 50, '눈', '당뇨', '루테인, 아스타잔틴');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 50, '눈', '고혈압/심혈관', '루테인, 오메가3');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 50, '눈', '골다공증/관절', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 50, '눈', '위장질환', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 50, '뼈', '당뇨', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 50, '뼈', '고혈압/심혈관', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 50, '뼈', '골다공증/관절', '칼슘, 비타민D');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 50, '뼈', '위장질환', '마그네슘, 비타민D');

INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 60, '피로/간', '당뇨', '비타민B, 밀크씨슬');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 60, '피로/간', '고혈압/심혈관', '밀크씨슬, 오메가3');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 60, '피로/간', '골다공증/관절', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 60, '피로/간', '위장질환', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 60, '체지방/혈당', '당뇨', '크롬, 알파리포산');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 60, '체지방/혈당', '고혈압/심혈관', '오메가3, 코엔자임Q10');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 60, '체지방/혈당', '골다공증/관절', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 60, '체지방/혈당', '위장질환', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 60, '눈', '당뇨', '루테인, 아스타잔틴');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 60, '눈', '고혈압/심혈관', '루테인, 오메가3');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 60, '눈', '골다공증/관절', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 60, '눈', '위장질환', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 60, '뼈', '당뇨', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 60, '뼈', '고혈압/심혈관', '종합비타민');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 60, '뼈', '골다공증/관절', '칼슘, 비타민D');
INSERT INTO RULE_TB (RULE_ID, RULE_AGE, RULE_INTEREST, RULE_DISEASE, RULE_RECOMMEND)
VALUES (RULE_TB_SEQ.NEXTVAL, 60, '뼈', '위장질환', '마그네슘, 비타민D');
COMMIT;